Update libraries for Rust 1.61 + Cargo 2021 edition
mcountryman/auth0-management pull request #6
Opened 2022-09-12 04:26 UTC by i-mann

Updated libraries to rust 1.61 and Cargo 2021. Updated to use `main` as default branch, and updated GitHub actions appropriately. Removed redundant/non-compiling tests.

Note that the tests weren't truly unit tests, they only tested the failure case and they depended on network configuration.

2024-08-30 13:38 UTC, mcountryman requested changes
Looks pretty good thanks.

The only thing I'd say really needs to change here is the removal of the integration tests.  Because we are doing things by hand we want some mechanism to validate the API.  

Yeah the tests are prone to failure and require a sandbox Auth0 tenant but, it's worth it IMO.

The only other alternative I could think of is using an Auth0 verified mock server setup to  reduce flakiness and the need for credentials.

2024-08-30 13:38 UTC, mcountryman commented on src/lib.rs
> +//!     .domain(env:var("AUTH0_DOMAIN"))
I'm pretty sure this will fail when running/building `Doc-tests`.  `env::var` returns a `Result`, `Auth0Builder::domain` takes a `&str`.

TBH `env!` probably isn't much better

2024-08-30 13:38 UTC, mcountryman commented on tests/helpers.rs
Integration tests are valid especially when writing API wrappers by hand.  Unless there's a good alternative to validate code conforms with Auth0's API I'd prefer to keep this around.

2024-08-30 13:38 UTC, mcountryman commented on src/users/users_find.rs
> +  #[serde(skip_serializing_if = "Sort::is_empty")]
lol I can't spell

2024-08-30 13:38 UTC, mcountryman commented on .github/workflows/test.yml
> +#        with:gs
Is this `with:gs` thing a typo?

2024-09-01 23:45 UTC, i-mann commented
Hi Marvin,
I'm no longer involved with this fork/codebase/organisation - so this PR can probably be closed, I'm not going to progress on it further. The team is working on the fork here: https://github.com/WORK180/auth0-management/tree/main

2024-09-03 13:30 UTC, closed without merging